name: Math Utility Repo applying CI # name : tương đương Console.log ghi lại nhật kí chạy các lệnh

on:
  push:
    branches: [ "main" ]       # Bất kì ai push code lên nhánh main, kho code chính
  pull_request:
    branches: [ "main" ]

jobs:                          # thì tự động thực thi các lệnh ở dưới đây
  build:                       # build app -> .jar .war bằng cách
                               # 1. Mượn 1 server bên Mỹ, cài sẵn giùm OS Ubuntu 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    # 2. Có server rồi, download code từ GH về server này
    - name: Set up JDK 21   - Mượn JDK 21          # 3. cho mượn cái JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'                    # 4. Khai báo version JDK ứng với file pom.xml
        distribution: 'temurin'                # 5. Mượn Maven, chạy lệnh đóng gói, test luôn xanh đỏ
        cache: maven
    - name: Build with Maven  - Tạo file .jar .war
      run: mvn -B package --file pom.xml

    
